// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assistente_de_Instalação.Models;

public partial class VcConfigura
{
    public string Desconto { get; set; }

    public string Garcom { get; set; }

    public string Vendedor { get; set; }

    public string Entrega { get; set; }

    public string Caderneta { get; set; }

    public string Cliente { get; set; }

    public string PistOtica { get; set; }

    public string Aprazo { get; set; }

    public string UsaEst { get; set; }

    public string FechaComp { get; set; }

    public double Servico { get; set; }

    public int TempInat { get; set; }

    public string ProgCom { get; set; }

    public int QtTurno { get; set; }

    public double Taxa { get; set; }

    public int Posicoes { get; set; }

    public string Repique { get; set; }

    public string Comanda { get; set; }

    public string Enviavenda { get; set; }

    public string Enviaturno { get; set; }

    public string Cupons { get; set; }

    public string Impcancel { get; set; }

    public string Paracontas { get; set; }

    public string Funcitens { get; set; }

    public string Impserv { get; set; }

    public string Mensaserv { get; set; }

    public string Usaprop { get; set; }

    public string Cponto { get; set; }

    public double Valmaximo { get; set; }

    public double Valconf { get; set; }

    public int Tempoesp { get; set; }

    public int Posiaomin { get; set; }

    public int Posiaomax { get; set; }

    public double Servent { get; set; }

    public string Descserv { get; set; }

    public string Descrep { get; set; }

    public string Mesaserv { get; set; }

    public string Dividep { get; set; }

    public int Nivelcanc { get; set; }

    public int Niveldesc { get; set; }

    public string Vergz { get; set; }

    public string Drivegz { get; set; }

    public string Duasli { get; set; }

    public string Tipofundo { get; set; }

    public string Leean2 { get; set; }

    public int Quartos { get; set; }

    public double Consumo { get; set; }

    public string Usacartao { get; set; }

    public string Trocamaq { get; set; }

    public string Pedesenha { get; set; }

    public string Pedido { get; set; }

    public string Descped { get; set; }

    public double Confqt { get; set; }

    public int Nivelgav { get; set; }

    public double Venda1 { get; set; }

    public double Comi1 { get; set; }

    public double Valor1 { get; set; }

    public double Venda2 { get; set; }

    public double Comi2 { get; set; }

    public double Valor2 { get; set; }

    public double Venda3 { get; set; }

    public double Comi3 { get; set; }

    public double Valor3 { get; set; }

    public double Venda4 { get; set; }

    public double Comi4 { get; set; }

    public double Valor4 { get; set; }

    public double Venda5 { get; set; }

    public double Comi5 { get; set; }

    public double Valor5 { get; set; }

    public double Venda6 { get; set; }

    public double Comi6 { get; set; }

    public double Valor6 { get; set; }

    public string Fidelidade { get; set; }

    public int Numfidel { get; set; }

    public string Usaatend { get; set; }

    public int Impentrega { get; set; }

    public string Gdprods { get; set; }

    public string Gdcli { get; set; }

    public int Tipoloja { get; set; }

    public int Lnfiscal { get; set; }

    public double Viss { get; set; }

    public string Recarga { get; set; }

    public string Recibo { get; set; }

    public string DescRec { get; set; }

    public string Inftitular { get; set; }

    public string Conjugado { get; set; }

    public int Nivcancite { get; set; }

    public int Nivdescite { get; set; }

    public int Nivservven { get; set; }

    public int Nivtaxaven { get; set; }

    public string Leicpf { get; set; }

    public string Mremota { get; set; }

    public string Informafs { get; set; }

    public string Impquant { get; set; }

    public string MensaCupom { get; set; }

    public string ImpEndFisc { get; set; }

    public string NumSeq { get; set; }

    public string Ceps { get; set; }

    public string RestTxt { get; set; }

    public string Acougue { get; set; }

    public string Identposi { get; set; }

    public int? Contador { get; set; }

    public string Entregaident { get; set; }

    public string Entregacenter { get; set; }

    public int TempoMaxEntrega { get; set; }

    public int TempoMaxPedido { get; set; }

    public string Termconsumo { get; set; }

    public int ProdBonif { get; set; }

    public string ConsumoMaior { get; set; }

    public int Cadernetadia { get; set; }

    public int Nivestoque { get; set; }

    public int Nivcontas { get; set; }

    public int Nivsangria { get; set; }

    public string Confsaida { get; set; }

    public string Bloqconsumo { get; set; }

    public double Maxconsu { get; set; }

    public int Nivelexec { get; set; }

    public string Viasterm { get; set; }

    public int Numviasterm { get; set; }

    public string Gcombo { get; set; }

    public int Niveltrans { get; set; }

    public int Nivelrposi { get; set; }

    public string Cancparcial { get; set; }

    public string Descesp { get; set; }

    public int Valdescesp { get; set; }

    public string Stre { get; set; }

    public string Precbal { get; set; }

    public string Ticlocal { get; set; }

    public string Usacatraca { get; set; }

    public string Endcatraca { get; set; }

    public string Conprodpaf { get; set; }

    public string Atendif { get; set; }

    public string Recgt { get; set; }

    public string Mglegal { get; set; }

    public string Rjmania { get; set; }

    public string Usapaf { get; set; }

    public string Trocattipos { get; set; }

    public string Zeraseq { get; set; }

    public string Consumochb { get; set; }

    public int Nivelcadcon { get; set; }

    public int Nivelvalcon { get; set; }

    public string Dddpadrao { get; set; }

    public string Cobraservent { get; set; }

    public string Cobraservcon { get; set; }

    public string Cartaoseis { get; set; }

    public string UsaComSerie { get; set; }

    public string ConfHorario { get; set; }

    public string IncluiCasal { get; set; }

    public string UsaArqImpPalm { get; set; }

    public string UsaArqImpTerm { get; set; }

    public string TurnoSemPos { get; set; }

    public string LetraC { get; set; }

    public int MaxDescPerc { get; set; }

    public string Notalegal { get; set; }

    public string Paraibalegal { get; set; }

    public string Progcred { get; set; }

    public string Servisento { get; set; }

    public string Mostraval { get; set; }

    public string UsaArqImpTouch { get; set; }

    public string Tpimp { get; set; }

    public string Tpemis { get; set; }

    public string Tpamb { get; set; }

    public string Fimnfe { get; set; }

    public string Proemi { get; set; }

    public string Modnfe { get; set; }

    public string Serienfe { get; set; }

    public string Numininfe { get; set; }

    public string Verprocnfe { get; set; }

    public string Certificado { get; set; }

    public string Logodanfe { get; set; }

    public string Ufwebservice { get; set; }

    public string Hostproxy { get; set; }

    public string Portaproxy { get; set; }

    public string Usuarioproxy { get; set; }

    public string Servsmtp { get; set; }

    public string Portasmtp { get; set; }

    public string Usuariosmtp { get; set; }

    public string Senhasmtp { get; set; }

    public string Segurasmtp { get; set; }

    public string Assuntoemail { get; set; }

    public string Mensagememail { get; set; }

    public string Novoestoque { get; set; }

    public string Impconta { get; set; }

    public int Addcodigo { get; set; }

    public int NivelFila { get; set; }

    public string UsaFila { get; set; }

    public string ControlaAbreTerm { get; set; }

    public string LetraComanda { get; set; }

    public string PosicaoReferencia { get; set; }

    public string ComandaPreCad { get; set; }

    public string Subbalanca { get; set; }

    public int NivelTransfPos { get; set; }

    public string MenuTablet { get; set; }

    public string Obsgrupo { get; set; }

    public int Nivellimpab { get; set; }

    public string Mercadoescolhido { get; set; }

    public string Exigenumpess { get; set; }

    public string Bloqtransfere { get; set; }

    public string Descavalor { get; set; }

    public string Comprovantetransf { get; set; }

    public string Comprovantecanc { get; set; }

    public int Impcomprovante { get; set; }

    public string Verificadoc { get; set; }

    public string UsacatracaTecnibra { get; set; }

    public string Msgnfce { get; set; }

    public string MargemEscolhido { get; set; }

    public string BloqConvenio { get; set; }

    public string UsaPrepago { get; set; }

    public int? ValidadeCredito { get; set; }

    public string UsaValidadeCredito { get; set; }

    public int Nivelcredito { get; set; }

    public string NimpCanc { get; set; }

    public string UsaVirtual { get; set; }

    public string UsaNumAle { get; set; }

    public string UsaEtiquetaPedido { get; set; }

    public string CodVanucci { get; set; }

    public string CodDcs { get; set; }

    public string UsaCatracaBio { get; set; }

    public string ImpCadSat { get; set; }

    public string UsaCest { get; set; }

    public DateTime? DataUsaCest { get; set; }

    public string ConfigValdra { get; set; }

    public string CentavosPag { get; set; }

    public string OrdemPag { get; set; }

    public string TrocaD { get; set; }

    public string CompValCart { get; set; }

    public string UsaModTefCappta { get; set; }

    public int Nivelbairros { get; set; }

    public string MostraSoCpf { get; set; }

    public string NimpConfFecgamento { get; set; }

    public string ObsMaisComanda { get; set; }

    public string DescAntEntrega { get; set; }

    public string CancSemSenhaEnviadoN { get; set; }

    public string AbateValorCadastrado { get; set; }

    public string Reduzinfocad { get; set; }

    public int Nivelverpessoas { get; set; }

    public string UsaDcs { get; set; }

    public string ServerRel { get; set; }

    public string ImpEstoqFechamento { get; set; }

    public string MostraFecha { get; set; }

    public string UsaCatracaHenry { get; set; }

    public string UsaControlFila { get; set; }

    public string MostraDinFecha { get; set; }

    public string PathGertec { get; set; }

    public string EnviaValorApuradoC { get; set; }

    public string NomePosicao { get; set; }

    public int Niveldesbloq { get; set; }

    public string LimitaComanda { get; set; }

    public int ComandaIni { get; set; }

    public int ComandaFin { get; set; }

    public int Niveltrocacon { get; set; }

    public string ConfigAirSoft { get; set; }

    public string PrMedioDeli { get; set; }

    public string ControlFila { get; set; }

    public string AlteraQtVenda { get; set; }

    public string DuplicaRemota { get; set; }

    public int Nivelfila1 { get; set; }

    public string SeparaMesaDeComanda { get; set; }

    public int MesaIni { get; set; }

    public int MesaFim { get; set; }

    public string Somacompleto { get; set; }

    public string IsentaGorjeta { get; set; }

    public string GarcomPorMesa { get; set; }

    public string OTelefone { get; set; }

    public string OEmail { get; set; }

    public string OComanda { get; set; }

    public string ORg { get; set; }

    public string NumSeqRandom { get; set; }

    public string ImprimeViaCompleta { get; set; }

    public int RemoImprimeViaCompleta { get; set; }

    public int ViasImprimeCompleto { get; set; }

    public string DescAnteConv { get; set; }

    public string MostraDataEprecoTicket { get; set; }

    public string NimpCancelRemota { get; set; }

    public string TelefoneRevenda { get; set; }

    public string SiteRevenda { get; set; }

    public string NomeRevenda { get; set; }

    public string CidadeRevenda { get; set; }

    public string EnderecoRevenda { get; set; }

    public string EstadoRevenda { get; set; }

    public string NomeSoftware { get; set; }

    public byte[] LogoEmpresa { get; set; }

    public string ConfigLaterrina { get; set; }

    public string ClientId { get; set; }

    public string ClientSecret { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string UsaIfood { get; set; }

    public string UsaContApi { get; set; }

    public string IpApiCont { get; set; }

    public int PortaIpApiCont { get; set; }

    public string ExigeEntregador { get; set; }

    public string CepAuto { get; set; }

    public string UsaPedidoDcs { get; set; }

    public string IdClientePedidoDcs { get; set; }

    public string UsuarioPedidoDcs { get; set; }

    public string SenhaPedidoDcs { get; set; }

    public string CadRapidoCliente { get; set; }

    public string UsaIntegracaoWabiz { get; set; }

    public string UsuarioWabiz { get; set; }

    public string SenhaWabiz { get; set; }

    public string PermiteDeparaProduto { get; set; }

    public string PermiteRejeitarPedido { get; set; }

    public string ImprimeViaMotoboy { get; set; }

    public string IsVerificado { get; set; }

    public string RegistraLog { get; set; }

    public int NivelBloqComanda { get; set; }

    public string UsaTelaUsuTouch { get; set; }

    public string UsaValFixoModQt { get; set; }

    public string UsaCtAssinadaFecha { get; set; }

    public string UrlApipedidoOnline { get; set; }

    public string BlockEntregaSemCep { get; set; }

    public string ImpProdsZeroPreConta { get; set; }

    public bool UsaIdentCliIntImp { get; set; }

    public string IdentCliIntImpIni { get; set; }

    public string IdentCliIntImpFin { get; set; }

    public string IdentCliIntImpDesc { get; set; }

    public bool ConsolidarTicket { get; set; }

    public bool ExibeObsTicket { get; set; }

    public string MsgEventoTicket { get; set; }

    public int NViasTicket { get; set; }

    public bool TicketOcabra { get; set; }

    public bool UsaDivProdR { get; set; }

    public int? PosIniDivProdR { get; set; }

    public int? PosFinDivProdR { get; set; }

    public bool DetPreConta { get; set; }

    public bool RestSubPorMaq { get; set; }

    public bool AltDupLprod { get; set; }

    public bool UsaNovaPromo { get; set; }

    public bool UsaRodizio { get; set; }

    public string IdentificaClienteSmartphone { get; set; }

    public bool ConsideraTotalFidelidade { get; set; }

    public string VApiIfood { get; set; }

    public bool ConvMesaBalcao { get; set; }

    public string NomeBalcao { get; set; }

    public int SangriaNumVias { get; set; }

    public string PedeMotivo { get; set; }

    public bool? MaisVendidosTouch { get; set; }

    public bool DescAntSobreProd { get; set; }

    public bool LiberaMaisDigCom { get; set; }

    public bool LiberaMaisDigComServico { get; set; }

    public string PisGorjeta { get; set; }

    public string CofinsGorjeta { get; set; }

    public bool IfoodOutrasFontes { get; set; }

    public bool? CancPedCaixa { get; set; }

    public bool CancCupSairPag { get; set; }

    public bool UseShipay { get; set; }

    public string ShipayAccessKey { get; set; }

    public string ShipaySecretKey { get; set; }

    public int ShipayNvlAprovar { get; set; }

    public int ShipayNlvCancelar { get; set; }

    public int ShipayNvlConsultaStatus { get; set; }

    public int ShipayNvlEstornar { get; set; }

    public bool? ShipayBloqAprovar { get; set; }

    public bool? ShipayBloqEstornarAutomatico { get; set; }

    public bool BloqDeliveryPosZero { get; set; }

    public bool LimitaObsImp { get; set; }

    public bool LimitaProdImp { get; set; }

    public bool? SublinharObsImp { get; set; }

    public bool? DelimitarObsImp { get; set; }

    public bool? FormataFracaoImp { get; set; }

    public bool? FormataQtdImp { get; set; }

    public bool IfoodInverteTemplatePizza { get; set; }

    public bool UsaDdireto { get; set; }

    public string DdiretoUsuario { get; set; }

    public string DdiretoSenha { get; set; }

    public string DdiretoIdFrn { get; set; }

    public string Ddiretokey { get; set; }

    public bool? DdiretoIntegrarCallCenter { get; set; }

    public bool? DdiretoIntegrarOcultos { get; set; }

    public bool PermiteStatusProduto { get; set; }

    public int NvlAtualizaStatusProduto { get; set; }

    public string TelPlantaoRevenda { get; set; }

    public bool? ExibeLabelTelefone { get; set; }

    public bool ExibeMsgSeImprimeViaClienteSat { get; set; }

    public bool ExibeTempoPosIdentificada { get; set; }

    public bool UsaPagamentoParcial { get; set; }

    public bool PartesPizzaRelFecha { get; set; }

    public string VersaoBd { get; set; }

    public bool UsaNovaFidelidade { get; set; }

    public bool ExibelinkSuporteOnline { get; set; }

    public string LinkSuporteOnline { get; set; }

    public bool UsaAcconDelivery { get; set; }

    public string AcconEmail { get; set; }

    public string AcconSenha { get; set; }

    public string AcconIdRede { get; set; }

    public bool UsaAnotaAi { get; set; }

    public string AnotaAiToken { get; set; }

    public string DtLk { get; set; }

    public bool UsaLinkAgenda { get; set; }

    public string LinkAgenda { get; set; }

    public bool InformaNsu { get; set; }

    public string UrlApiComunicacao { get; set; }

    public bool CapturaDePesoPelaApi { get; set; }

    public bool ApiTef { get; set; }

    public bool ComissaoAtend { get; set; }

    public bool OrdSubGrupoTouch { get; set; }

    public bool ExibeAtendPosicaoTicket { get; set; }

    public bool FinPedFechaCupom { get; set; }

    public bool ErroCdataSat { get; set; }

    public bool DespachaPedidoFechaCupom { get; set; }

    public DateTime DtEmiteCont { get; set; }

    public bool MotivoCancObrigatorio { get; set; }

    public string RepeteObs { get; set; }

    public bool NaoImprimirFechamento { get; set; }

    public bool DivideContaCupomFiscal { get; set; }

    public bool ExibeDescontoItemPreConta { get; set; }

    public bool MantemServDesItem { get; set; }

    public bool AjustaDiferencaServico { get; set; }

    public int NivelModoManualGestorPedidos { get; set; }

    public bool TentNovProdNencontrado { get; set; }
}