// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assistente_de_Instalação.Models;

public partial class VcMaquinas
{
    public int IdMaquina { get; set; }

    public string Gaveta { get; set; }

    public string Nomecomp { get; set; }

    public string Descricao { get; set; }

    public string Portacom { get; set; }

    public string Tipoimp { get; set; }

    public int Nlinhas { get; set; }

    public string Chave { get; set; }

    public string Balanca { get; set; }

    public string Combalan { get; set; }

    public string Confbalan { get; set; }

    public string Rf { get; set; }

    public string Tiposweda { get; set; }

    public string Microterm { get; set; }

    public string Microporta { get; set; }

    public string Microimp { get; set; }

    public int Micronum { get; set; }

    public string Microvelo { get; set; }

    public string Mtpasso { get; set; }

    public string Usaatalho { get; set; }

    public int Fator { get; set; }

    public string Daruma { get; set; }

    public string Elotech { get; set; }

    public string Abrecup { get; set; }

    public string Dircup { get; set; }

    public string Displa { get; set; }

    public string Toledo { get; set; }

    public string Prodigital { get; set; }

    public string Bemarest { get; set; }

    public string Tipopasso { get; set; }

    public string Fechaimp { get; set; }

    public string Impprod { get; set; }

    public string Repauto { get; set; }

    public string Sispalm { get; set; }

    public string Arqfilizola { get; set; }

    public string Subposicao { get; set; }

    public string Olivetti { get; set; }

    public string Novabalan { get; set; }

    public string Terminal { get; set; }

    public string Tela { get; set; }

    public string Pbruto { get; set; }

    public int Ncupons { get; set; }

    public int Viasent { get; set; }

    public string Notahot { get; set; }

    public string Impnf { get; set; }

    public string Stermica { get; set; }

    public string Sisbalauto { get; set; }

    public string Darumakg { get; set; }

    public string Vertef { get; set; }

    public string Prefisc { get; set; }

    public string Microterm1 { get; set; }

    public DateTime DataCad { get; set; }

    public string Gertec { get; set; }

    public string Shellbi { get; set; }

    public string Mf { get; set; }

    public string Willtech { get; set; }

    public string Kgauto { get; set; }

    public string Posicod { get; set; }

    public string TurnoSemPos { get; set; }

    public string GuilhotinaIf { get; set; }

    public string Kgautosob { get; set; }

    public string Bematerm { get; set; }

    public int Numtermtouch { get; set; }

    public string ArredondaEpson { get; set; }

    public string Velocidade { get; set; }

    public string Balancaquant { get; set; }

    public string Bloqsangria { get; set; }

    public DateTime? DtRedz { get; set; }

    public string UranoUdcPop { get; set; }

    public string Donuzauto { get; set; }

    public string Caminhodonuz { get; set; }

    public int Nfcecon { get; set; }

    public string UsaVanucci { get; set; }

    public string CupomVanucci { get; set; }

    public string CupomDupliVanucci { get; set; }

    public string CupomErroVanucci { get; set; }

    public string ImpRecIcms { get; set; }

    public int? LoteNfce { get; set; }

    public int? NumNfce { get; set; }

    public string AsgnSat { get; set; }

    public string CodSat { get; set; }

    public string NumCaixa { get; set; }

    public string PathImp { get; set; }

    public string PathArm { get; set; }

    public string CnpjVirtual { get; set; }

    public int? AmbienteNfce { get; set; }

    public string ConfigRipa { get; set; }

    public int? QtDigitosDv { get; set; }

    public string EnviaTrocaInt { get; set; }

    public string LayoutSat { get; set; }

    public string DigitoVerificadorRipa { get; set; }

    public string SomenteViasEntrega { get; set; }

    public string InverteCmdGaveta { get; set; }

    public string ApiSat { get; set; }

    public string DuasViasPreConta { get; set; }

    public string ImpPedidoNoSat { get; set; }

    public string UsarDadosMaquinaSat { get; set; }

    public string CnpjMaquinas { get; set; }

    public string Iemaquinas { get; set; }

    public int Frelacionado { get; set; }

    public string NegritaSat { get; set; }

    public int? IdHostImpLocal { get; set; }

    public string ApontaImpLocal { get; set; }

    public string NImpRemo { get; set; }

    public string ExpIfood { get; set; }

    public string NomeDllsat { get; set; }

    public bool UsaRestPosInte { get; set; }

    public int RestIntIni { get; set; }

    public int RestIntFin { get; set; }

    public int TouchPadrao { get; set; }

    public bool KgAutoTerminal { get; set; }

    public bool BalTororey { get; set; }

    public bool BloqueiaBalcao { get; set; }

    public string ShipayPosDesc { get; set; }

    public string ShipayClientId { get; set; }

    public bool ShipayTerminalStatus { get; set; }

    public bool ShipayPermiteConsulta { get; set; }

    public bool ShipayImprimirQrCode { get; set; }

    public bool TermAbertComandas { get; set; }

    public int NSerieNfce { get; set; }

    public string DuasViasPreContaEntrega { get; set; }

    public int? ApiTefIdTerminal { get; set; }

    public string UrlIntegradorDePedidos { get; set; }

    public int PortaGestorDePedidos { get; set; }

    public bool UsaIntegradorDePedidos { get; set; }

    public bool AbreApiSat { get; set; }

    public virtual ICollection<VcCupfecha> VcCupfecha { get; set; } = new List<VcCupfecha>();
}