// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Assistente_de_Instalação.Models;

public partial class VcProdutos
{
    public int IdProduto { get; set; }

    public string Produto { get; set; }

    public int IdUnidade { get; set; }

    public int IdSubgrupo { get; set; }

    public string Venda { get; set; }

    public string Estoue { get; set; }

    public string Aceitadec { get; set; }

    public double Percent1 { get; set; }

    public double Percent2 { get; set; }

    public double Eminimo { get; set; }

    public double Vminimo { get; set; }

    public double Pvenda { get; set; }

    public string Cproduto { get; set; }

    public string Cbarra { get; set; }

    public string Alicota { get; set; }

    public string Servico { get; set; }

    public string Compoe { get; set; }

    public string Divide { get; set; }

    public string Maior { get; set; }

    public string Atalho { get; set; }

    public string Saliq { get; set; }

    public string Scodncm { get; set; }

    public string Ssittrib { get; set; }

    public string Saliqipi { get; set; }

    public string Sreducalc { get; set; }

    public string Ssubtrib { get; set; }

    public string Saliqicms { get; set; }

    public string Observacoes { get; set; }

    public int Valedias { get; set; }

    public double Preco2 { get; set; }

    public DateTime? Dataini { get; set; }

    public DateTime? Datafin { get; set; }

    public string Balanca { get; set; }

    public double Preco3 { get; set; }

    public string Horai { get; set; }

    public string Horaf { get; set; }

    public string Semanai { get; set; }

    public string Semanaf { get; set; }

    public double Preco4 { get; set; }

    public string Icone { get; set; }

    public double Comissao { get; set; }

    public string Composto { get; set; }

    public string Automatico { get; set; }

    public string Observacao { get; set; }

    public double PrecoBon { get; set; }

    public string Manual { get; set; }

    public string Fabricacao { get; set; }

    public string Iat { get; set; }

    public string Prodauto { get; set; }

    public string Ticket { get; set; }

    public string Tribicms { get; set; }

    public double Alicred { get; set; }

    public string Modbc { get; set; }

    public double Redbc { get; set; }

    public double Bcop { get; set; }

    public string Modbcst { get; set; }

    public double Redbcst { get; set; }

    public double Margemaddst { get; set; }

    public double Icmsst { get; set; }

    public string Ufst { get; set; }

    public string Origem { get; set; }

    public string Motdes { get; set; }

    public double Iva { get; set; }

    public string Tipopis { get; set; }

    public string Tipocalcpis { get; set; }

    public double Aliquotapis { get; set; }

    public string Tipocalcpisst { get; set; }

    public double Aliquotapisst { get; set; }

    public string Tipocofins { get; set; }

    public string Tipocalccofins { get; set; }

    public double Aliquotacofins { get; set; }

    public string Tipocalccofinsst { get; set; }

    public double Aliquotacofinsst { get; set; }

    public double Icms { get; set; }

    public string Capncm { get; set; }

    public string Selecionado { get; set; }

    public int IdProdint { get; set; }

    public string Obrigaposicao { get; set; }

    public string Prodsob { get; set; }

    public string Ncm { get; set; }

    public int Ex { get; set; }

    public int IdInternet { get; set; }

    public string Cfop { get; set; }

    public double Margem { get; set; }

    public string PermiteTab { get; set; }

    public string CadastradoPor { get; set; }

    public string AlteradoPor { get; set; }

    public string ImpEtiqueta { get; set; }

    public string CstIcms { get; set; }

    public string CstPis { get; set; }

    public string CstCofins { get; set; }

    public double? VIcms { get; set; }

    public double? VIcmsst { get; set; }

    public double? PMvast { get; set; }

    public string MotDesIcms { get; set; }

    public string VBcstret { get; set; }

    public string VIcmsstret { get; set; }

    public double? VPis { get; set; }

    public string CobraCatraca { get; set; }

    public string Cest { get; set; }

    public double? ValorAbate { get; set; }

    public double QuantMax { get; set; }

    public double ValFixo { get; set; }

    public int? IdReceita { get; set; }

    public string ServicoAirSoft { get; set; }

    public string ProdPromo { get; set; }

    public double PrBalDeli { get; set; }

    public string EnviaMensagem { get; set; }

    public byte[] Foto { get; set; }

    public string IsCadAuto { get; set; }

    public string Pizza { get; set; }

    public string Combo { get; set; }

    public string Extra { get; set; }

    public double ValCombo { get; set; }

    public string ProdAutoCatraca { get; set; }

    public string IsAcomp { get; set; }

    public bool FlCombinarPromo { get; set; }

    public bool FlHoraIniHoraFin { get; set; }

    public bool FlPromoData { get; set; }

    public bool FlPromoSemana { get; set; }

    public bool FlPromoHora { get; set; }

    public bool FlPromoDiaSemana { get; set; }

    public bool PromoDom { get; set; }

    public bool PromoSeg { get; set; }

    public bool PromoTer { get; set; }

    public bool PromoQua { get; set; }

    public bool PromoQui { get; set; }

    public bool PromoSex { get; set; }

    public bool PromoSab { get; set; }

    public decimal PrecoPromo { get; set; }

    public decimal PrecoDiaSemana { get; set; }

    public bool ProdRodizio { get; set; }

    public string CBenef { get; set; }

    public bool ProdComoServico { get; set; }

    public bool CalculaProdPorTempo { get; set; }

    public string ExternalCode { get; set; }

    public string IgnoraTouch { get; set; }

    public bool FlManterQtd { get; set; }

    public bool FlMultiplaVlFixo { get; set; }

    public bool IsPizzaMontagem { get; set; }

    public bool IsComboMontagem { get; set; }

    public bool IsPizza { get; set; }
}